question_data = [
    {"type": "boolean", "difficulty": "medium", "category": "Geography",
     "question": "The Sonoran Desert is located in eastern Africa.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Mythology",
     "question": "According to Norse mythology, Loki is a mother.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Animals",
     "question": "A flock of crows is known as a homicide.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "The word &quot;Inception&quot; came from the 2010 blockbuster hit &quot;Inception&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Science &amp; Nature",
     "question": "&quot;Tachycardia&quot; or &quot;Tachyarrhythmia&quot; refers to a resting heart-rate near or over 100 BPM.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Animals",
     "question": "Rabbits are carnivores.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "In the video game &quot;Splatoon&quot;, the playable characters were originally going to be rabbits instead of squids.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Music",
     "question": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Music",
     "question": "&quot;Twenty One Pilots&quot; made the song &quot;The Motion&quot; featuring Sampha.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "General Knowledge",
     "question": "The word &quot;news&quot; originates from the first letters of the 4 main directions on a compass (North, East, West, South).",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
     "question": "Hungary is the only country in the world beginning with H.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Vehicles",
     "question": "The Honda Motor Corporation originates in Japan",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "General Knowledge",
     "question": "A pencil&#039;s lead is typically made from graphite, not lead",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Film",
     "question": "The weapon Clint Eastwood uses in &quot;Dirty Harry&quot; was a .44 Automag.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "History",
     "question": "Japan was part of the Allied Powers during World War I.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "General Knowledge",
     "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Music",
     "question": "3 members of 2 Live Crew were arrested for playing songs from their album, As Nasty As They Wanna Be, live.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Science &amp; Nature",
     "question": "The Earth revolves around the Sun in one year.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Music",
     "question": "Pink Guy&#039;s debut album was &quot;Pink Season&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Science &amp; Nature",
     "question": "In the periodic table, Potassium&#039;s symbol is the letter K.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "Throughout the entirety of &quot;Dragon Ball Z&quot;, Goku only kills two characters: a miniboss named Yakon and Kid Buu.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Geography",
     "question": "The capital of the US State Ohio is the city of Chillicothe.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "POLYBIUS is a myth arcade cabinet/game",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "General Knowledge",
     "question": "Only a small percentage of the world&#039;s population is lactose intolerant.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Television",
     "question": "In the animated series Futurama, the character Phllip J. Fry is his own grandfather.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Vehicles",
     "question": "BMW M GmbH is a subsidiary of BMW AG that focuses on car performance.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Sports",
     "question": "During Wimbledon, spectators in the grounds can buy the tennis balls that have been used in matches.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "General Knowledge",
     "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Science: Computers",
     "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Music",
     "question": "Muse is a British (English) rock band",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "The Fiat Multipla is a drivable car in &quot;Forza Horizon 3&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "General Knowledge",
     "question": "NCIS stands for &quot;Navy Corps Investigative Service&quot;",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; was released in 2004.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "question": "Sargon II, a king of the Neo-Assyrian Empire, was a direct descendant of Sargon of Akkad.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "The edutainment video game series character, Carmen Sandiego, is partially named after Brazilian actress, Carmen Miranda.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "During pre-production of &quot;Super Mario Bros.&quot;, Mario originally was meant to shoot bullets.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Science &amp; Nature",
     "question": "Centripetal force is an apparent force that acts outward on a body moving around a center, arising from the body&#039;s inertia.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Music",
     "question": "&quot;The Division Bell&quot; is the final album of the progressive rock band Pink Floyd.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Comics",
     "question": "Deadpool&#039;s identity is Slade Wilson.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "The ADAM collecters in the Bioshock series are known as Little Sisters.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "The PlayStation was originally a joint project between Sega and Sony that was a Sega Genesis with a disc drive.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Science: Gadgets",
     "question": "During the  early parts of the Vietnam War the M16 had a record for having bad reliability",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "The Indie Game Development Studio Cing, developers of Hotel Dusk and Last Window, went bankrupt on March 1st, 2010.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "In the &quot;Toaru Kagaku no Railgun&quot; anime,  espers can only reach a maximum of level 6 in their abilities.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "In Splatoon, the Squid Sisters are named Tako and Yaki.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Science &amp; Nature",
     "question": "Salt is 100% composed of Sodium.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Sports",
     "question": "Skateboarding was included in the 2020 Summer Olympics in Tokyo.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Television",
     "question": "In the Season 1 SpongeBob Squarepants episode, &quot;Help Wanted,&quot; the song &quot;Living in the Sunlight&quot; by Tiny Tim can be heard.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Video Games",
     "question": "Unturned originally started as a Roblox game.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
     "question": "The General Motors EV1 was the first street-legal production electric vehicle.",
     "correct_answer": "False", "incorrect_answers": ["True"]}]
